site_name: Alpacasay
site_description: A fun CLI tool that displays messages with ASCII alpacas - like cowsay but with alpacas!
site_url: https://mazzma12.github.io/alpacasay
repo_url: https://github.com/mazzma12/alpacasay
repo_name: mazzma12/alpacasay

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            # Show source code links
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            heading_level: 2

            # Function/method documentation
            show_signature_annotations: true
            show_return_annotation: true
            separate_signature: true

            # Source code linking
            show_source_link: true
            source_link_repository: "https://github.com/mazzma12/alpacasay"
            source_link_directory: "src"

            # Documentation features
            docstring_style: "google"
            docstring_section_style: "table"
            show_category_heading: true
            group_by_category: true

            # Show everything
            filters: ["!^_"]  # Hide private methods starting with _
            members_order: "alphabetical"
            show_submodules: true
