name: Code Quality

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/code-quality.yml"
      - "pyproject.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/code-quality.yml"
      - "pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.8.12"
          enable-cache: true
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run linting
        run: |
          uv run ruff check .

      - name: Run formatting check
        run: |
          uv run ruff format --check .

      - name: Run tests
        run: |
          uv run pytest -v --cov=alpacasay --cov-report=xml --cov-report=term-missing

      - name: Build package
        run: |
          uv build
